# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TopEvent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'FirebaseAuth', '= 9.1.0'
pod 'GoogleSignIn', '= 6.2.2'
pod 'Alamofire'
  # Pods for TopEvent

end
